{
 "title": "Micronaut",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{area=\"heap\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!=\"UNMATCHED_URI\"}[5m])) by (status, uri)",
     "legendFormat": "{{status}} {{uri}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(http_server_requests_seconds_max{uri!=\"UNMATCHED_URI\"}) by (status, uri)",
     "legendFormat": "{{status}} {{uri}}"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "repeat": "jvm_memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{id=~\"$jvm_memory_pool_heap\"}) by (id)",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{id=~\"$jvm_memory_pool_heap\"}) by (id)",
     "legendFormat": "committed"
    }
   ]
  }
 ]
}